### ISSUE TITLE
remove "async" and other unwanted require statements

### ISSUE THREAD

**Issue by TDA** [rwky/grunt-remarkable#1]
When `grunt-remarkable` is used without installing `async` it throws an error, so this should be declared as a dependency or devDep.
From https://github.com/rwky/grunt-remarkable/blob/master/tasks/remarkable.coffee#L4
### Error thrown:

```
$ grunt remarkable
Loading "remarkable.coffee" tasks...ERROR
>> Error: Cannot find module 'async'
Loading "remarkable.js" tasks...ERROR
>> Error: Cannot find module 'async'
```

EDIT: On close inspection, these werent required. So remove `async`.

@rwky

**Comment by pdehaan** [comment]
Actually, I don't even think the source code uses any of these dependencies:

``` coffee
    fs = require 'fs'
    async = require 'async'
    os = require('os')
    util = require('util')
```

&mdash; via [/tasks/remarkable.coffee:3-6](https://github.com/rwky/grunt-remarkable/blob/a833d6324ae1c83190ab5fcfd26f1e5038444d7d/tasks/remarkable.coffee#L3-L6)
